export const alertConstants = {
    LOGIN_SUCCESS:"ALERT_SUCCESS",
    // REGISTER1_SUCCESS:'ALERT_SUCCESS',
    // REGISTER2_SUCCESS:'ALERT_SUCCESS',
    // REGISTER3_SUCCESS:'ALERT_SUCCESS',
    // REGISTER4_SUCCESS:'ALERT_SUCCESS',
    LOGIN_ERROR:"ALERT_ERROR",
    // REGISTER1_ERROR:'ALERT_ERROR',
    // REGISTER2_ERROR:'ALERT_ERROR',
    // REGISTER3_ERROR:'ALERT_ERROR',
    // REGISTER4_ERROR:'ALERT_ERROR',
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};
